2024-02-01 15:04:08,337:dict_example:Key not found in the dictionary.
Traceback (most recent call last):
  File "C:\Users\ananya.bhat\PythonPractice\Loggings\logger_eg.py", line 10, in dict_example
    value = my_dict["d"]
            ~~~~~~~^^^^^
KeyError: 'd'
2024-02-01 15:04:49,835:dict_example:Key not found in the dictionary.
Traceback (most recent call last):
  File "C:\Users\ananya.bhat\PythonPractice\Loggings\logger_eg.py", line 10, in dict_example
    value = my_dict["d"]
            ~~~~~~~^^^^^
KeyError: 'd'
